In [1]:
import numpy as np

In [3]:
rmin = 1
rmax = 10
nd = 10
nr = 50

dd_rs = np.random.random_sample(nd*nd/2)*(rmax-rmin) + rmin
dr_rs = np.random.random_sample(nd*nr/2)*(rmax-rmin) + rmin
rr_rs = np.random.random_sample(nr*nr/2)*(rmax-rmin) + rmin

In [4]:
def tophat(r, bins, val):
    K = len(bins)-1
    u = np.zeros(K)
    ins = -1
    for bb in range(K):
        if r>=bins[bb] and r<bins[bb+1]:
            ins = bb
            break
    if ins>=0 and ins<K:
        u[ins] = val
    return u

In [5]:
def outer(u):
    K = len(u)
    out = np.zeros((K,K))
    for i in range(K):
        for j in range(K):
            out[i][j] = u[i]*u[j]
    return out

In [17]:
K = 3
bins = np.logspace(np.log10(rmin), np.log10(rmax), K+1)

val = 1
udd = np.zeros(K)
for r in dd_rs:
    udd += tophat(r, bins, val)

udr = np.zeros(K)
for r in dr_rs:
    udr += tophat(r, bins, val)

urr = np.zeros(K)
uqq = np.zeros((K,K))
uoo = np.zeros((K,K))

for r in rr_rs:
    u = tophat(r, bins, val)
    urr += u
    uqq += np.einsum('i,j', u, u)
    #uoo += outer(u)
    
dd = udd/(nd*nd)
dr = 2*udr/(nd*nr)
rr = urr/(nr*nr)
qq = uqq/(nr*nr)
qqinv = np.matrix(qq).I
numerator = dd - 2*dr + rr
a = np.matmul(qqinv, numerator)

x = 0.5*(bins[1:]+bins[:-1])
bases = []
for xx in x:
    bases.append(tophat(xx, bins, val))
xi = np.matmul(a, np.array(bases).T)
xi = np.squeeze(np.asarray(xi))

print udd
print udr
print urr
print uqq
print a
print xi

[ 4. 16. 30.]
[ 27.  71. 152.]
[161. 344. 745.]
[[161.   0.   0.]
 [  0. 344.   0.]
 [  0.   0. 745.]]
[[-1.73291925 -1.96511628 -2.0738255 ]]
[-1.73291925 -1.96511628 -2.0738255 ]


In [18]:
K = 3
bins = np.logspace(np.log10(rmin), np.log10(rmax), K+1)

val = 0.1
udd = np.zeros(K)
for r in dd_rs:
    udd += tophat(r, bins, val)

udr = np.zeros(K)
for r in dr_rs:
    udr += tophat(r, bins, val)

urr = np.zeros(K)
uqq = np.zeros((K,K))
uoo = np.zeros((K,K))

for r in rr_rs:
    u = tophat(r, bins, val)
    urr += u
    uqq += np.einsum('i,j', u, u)
    #uoo += outer(u)

dd = udd/(nd*nd)
dr = 2*udr/(nd*nr)
rr = urr/(nr*nr)
qq = uqq/(nr*nr)
qqinv = np.matrix(qq).I
numerator = dd - 2*dr + rr
a = np.matmul(qqinv, numerator)

x = 0.5*(bins[1:]+bins[:-1])
bases = []
for xx in x:
    bases.append(tophat(xx, bins, val))
xi = np.matmul(a, np.array(bases).T)
xi = np.squeeze(np.asarray(xi))

print udd
print udr
print urr
print uqq
print a
print xi

[0.4 1.6 3. ]
[ 2.7  7.1 15.2]
[16.1 34.4 74.5]
[[1.61 0.   0.  ]
 [0.   3.44 0.  ]
 [0.   0.   7.45]]
[[-17.32919255 -19.65116279 -20.73825503]]
[-1.73291925 -1.96511628 -2.0738255 ]
