In [1]:
import numpy as np

In [2]:
rmin = 1
rmax = 10
nd = 10
nr = 50

dd_rs = np.random.random_sample(nd*nd/2.)*(rmax-rmin) + rmin
dr_rs = np.random.random_sample(nd*nr/2.)*(rmax-rmin) + rmin
rr_rs = np.random.random_sample(nr*nr/2.)*(rmax-rmin) + rmin

In [5]:
def tophat(r, bins):
    K = len(bins)-1
    u = np.zeros(K)
    ins = -1
    for bb in range(K):
        if r>=bins[bb] and r<bins[bb+1]:
            ins = bb
            break
    if ins>=0 and ins<K:
        u[ins] = 1
    return u

In [14]:
def outer(u):
    K = len(u)
    out = np.zeros((K,K))
    for i in range(K):
        for j in range(K):
            out[i][j] = u[i]*u[j]
    return out

In [15]:
K = 3
bins = np.logspace(np.log10(rmin), np.log10(rmax), K+1)

udd = np.zeros(K)
for r in dd_rs:
    udd += tophat(r, bins)

udr = np.zeros(K)
for r in dr_rs:
    udr += tophat(r, bins)

urr = np.zeros(K)
uqq = np.zeros((K,K))
uoo = np.zeros((K,K))

for r in rr_rs:
    u = tophat(r, bins)
    urr += u
    uqq += np.einsum('i,j', u, u)
    uoo += outer(u)

    
print udd
print udr
print urr
print uqq
print uoo

[1. 2. 7.]
[ 2.  7. 11.]
[ 5. 11. 34.]
[[ 5.  0.  0.]
 [ 0. 11.  0.]
 [ 0.  0. 34.]]
[[ 5.  0.  0.]
 [ 0. 11.  0.]
 [ 0.  0. 34.]]
